### ISSUE TITLE
回答问题是出现版本旧的提示了

### ISSUE THREAD

**Issue by lianyitj** [Meteo-Pig/CursorCode#11]
是不是快不能用了？
You are on an old version of Cursor that will be deprecated soon. Please download the latest version at cursor.so to get new features and continued support.
![GFBK{3AMXDR$JE_D J TCV7](https://user-images.githubusercontent.com/10227648/228996988-cf27863e-2a0d-4763-91c7-ad2d9c1f7a3c.png)

**Comment by Meteo-Pig** [comment]
暂不影响使用，新版的cursor会强制登录后才能使用。

**Comment by lianyitj** [comment]
确实是，必须登录了，而且还有每月100次的限制了，看来这个cursor也快不行了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月31日(星期五) 下午2:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Meteo-Pig/CursorCode] 回答问题是出现版本旧的提示了 (Issue #11)





 
暂不影响使用，新版的cursor会强制登录后才能使用。

**Comment by Meteo-Pig** [comment]
我插件里面集成的还能继续使用，它暂时不会这么快就抛弃老用户，看后期怎么发展吧，反正也开始支持使用gpt的token了

**Comment by Meteo-Pig** [comment]
我这个插件的接口还是继续用老版本的，只是会有些提示，无视就好，不影响使用，好处就是不用登录，后期如果这个接口被和谐了，就只能登录使用或者用gpt代替了。

**Comment by dev-bz** [comment]
> 我这个插件的接口还是继续用老版本的，只是会有些提示，无视就好，不影响使用，好处就是不用登录，后期如果这个接口被和谐了，就只能登录使用或者用gpt代替了。

@Meteo-Pig 在请求头更新一下Cursor版本为0.1.11就可以暂时跳过这个警告，最好是要跳过这条警告，因为它似乎能干扰整个对话。

**Comment by Meteo-Pig** [comment]
> @Meteo-Pig 在请求头User-Agent更新一下Cursor版本为0.1.11就可以暂时跳过这个警告，最好是要跳过这条警告，因为它似乎能干扰整个对话。

如果改为新版接口，就需要登录才能使用了。

**Comment by dev-bz** [comment]
> > @Meteo-Pig 在请求头User-Agent更新一下Cursor版本为0.1.11就可以暂时跳过这个警告，最好是要跳过这条警告，因为它似乎能干扰整个对话。
> 
> 如果改为新版接口，就需要登录才能使用了。

嗯，刚刚才发现，11也开始提警告了，12要登陆了，一个月100个积分根本不够用。

**Comment by Meteo-Pig** [comment]
@dev-bz 所以插件的接口还是能使用的，不管提示就行了，除非后期旧版接口废了，只能改成登录的接口了。

**Comment by Meteo-Pig** [comment]
已更新最新版本。
