### ISSUE TITLE
能否添加 cursor 登录机制

### ISSUE THREAD

**Issue by tiomke** [Meteo-Pig/CursorCode#12]
购买cursor会员可以解除对话次数上限，但是cursor本身应用并不好用，大大能否添加对cursor登录的支持呢？

---
或者允许用户提供 refreshToken 存放路径，在请求前挂上 Bearer 验证，不知道是否可行

**Comment by Meteo-Pig** [comment]
已添加登录机制。

**Comment by tiomke** [comment]
万分感谢！
