### ISSUE TITLE
使用超出上限，好像用不了了

### ISSUE THREAD

**Issue by bjzhb666** [Meteo-Pig/CursorCode#14]
![image](https://user-images.githubusercontent.com/71651717/231409464-845fc88d-b754-42bd-a6a1-c88a9cda57e2.png)

**Comment by little-weakduck** [comment]
我也是

**Comment by lianyitj** [comment]
我也是

**Comment by Mad-hu** [comment]
被割腰子,估计噶了

**Comment by lianyitj** [comment]
可惜了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月13日(星期四) 上午10:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Meteo-Pig/CursorCode] 使用超出上限，好像用不了了 (Issue #14)





 
被割腰子,估计噶了

**Comment by Meteo-Pig** [comment]
已经临时更新一版最新接口，与cursor官方同步，添加登录机制，在插件上面登录即可，请及时更新插件为最新版本。
