### ISSUE TITLE
在vscode的ssh 远程连接服务器写代码的情况下无法使用.

### ISSUE THREAD

**Issue by xueweijian** [Meteo-Pig/CursorCode#15]
插件区域现实空白.只能在vscode本地写代码时候是正常的.但我们是后端,很多时候再 连接虚拟机或 wsl之类的 linux,里面写代码.

**Comment by Donkdot** [comment]
同样的问题！ @Meteo-Pig 希望得到您的解答！

**Comment by Meteo-Pig** [comment]
已经解决ssh问题，请更新到插件最新版本。
