### ISSUE TITLE
支持持久化存储prompt

### ISSUE THREAD

**Issue by adndyxu** [Meteo-Pig/CursorCode#22]
支持插入一段固定的prompt吗，这样不用每次都写一遍了
cursor原本自带功能，蛮实用的

**Comment by Dragon1573** [comment]
![image](https://user-images.githubusercontent.com/49941141/233844586-2535a7b1-3c4c-45d9-906c-bfa74726e598.png)

Cursor IDE 里除了右侧栏提供的 Chat ，还可以切换到 More 选项卡，这个 Instructions 会对每一个对话生效，确实非常有用，锁定回复的编程语言、格式之类的很方便。

**Comment by Meteo-Pig** [comment]
已经添加prompt，请更新至最新版。
