### ISSUE TITLE
好像不能用了，每次都让登录

### ISSUE THREAD

**Issue by hlblade** [Meteo-Pig/CursorCode#28]
之前用得挺好的，今天突然每次都让登录，即使跳出的网页和插件都提示登录成功还是无法使用。

**Comment by glaye** [comment]
一样

**Comment by hxshandle** [comment]
一样的问题啊，无法使用了

**Comment by George-pang** [comment]
我也是跳出网页登录成功后，vscode插件还是显示要登录

**Comment by wxh199600000** [comment]
我 也是

**Comment by hbxiaobo** [comment]
+1

**Comment by EngineerXiang** [comment]
+1

**Comment by nathubs** [comment]
+1

**Comment by Tianhezhiwai** [comment]
+1

**Comment by Meteo-Pig** [comment]
已经修复，请更新至最新版。

**Comment by wxh199600000** [comment]
> 

这个登录cursor就行了吗

我出现了 Request failed with status code 404

**Comment by Meteo-Pig** [comment]
> 

右下角出现登录成功弹窗就行了

**Comment by wxh199600000** [comment]
> > 
> 
> 右下角出现登录成功弹窗就行了

一直没显示就一直尝试登陆吗

**Comment by wxh199600000** [comment]
如果用的github登录的cursor，能通过登陆这个的githu账户登陆吗，我的意志不显示右下角的弹窗，是这个问题吗

**Comment by Meteo-Pig** [comment]
> 如果用的github登录的cursor，能通过登陆这个的githu账户登陆吗，我的意志不显示右下角的弹窗，是这个问题吗

是的，我使用的是cursor的账户，我现在把原来的浏览器登录加上，稍等。

**Comment by wxh199600000** [comment]
> > 如果用的github登录的cursor，能通过登陆这个的githu账户登陆吗，我的意志不显示右下角的弹窗，是这个问题吗
> 
> 是的，我使用的是cursor的账户，我现在把原来的浏览器登录加上，稍等。

谢谢大佬，我还发现登陆的密码是明示的，可能存在泄露的问题，十分感谢，您的产品非常好用

**Comment by Meteo-Pig** [comment]
> > > 如果用的github登录的cursor，能通过登陆这个的githu账户登陆吗，我的意志不显示右下角的弹窗，是这个问题吗
> > 
> > 
> > 是的，我使用的是cursor的账户，我现在把原来的浏览器登录加上，稍等。
> 
> 谢谢大佬，我还发现登陆的密码是明示的，可能存在泄露的问题，十分感谢，您的产品非常好用

已经添加了浏览器登录，这个版本是重构的，有些功能还没加上。新增密码登录是因为很多人使用ssh远程无法使用，没想到你们是GitHub登录，考虑不周了。

**Comment by wxh199600000** [comment]
> > > > 如果用的github登录的cursor，能通过登陆这个的githu账户登陆吗，我的意志不显示右下角的弹窗，是这个问题吗
> > > 
> > > 
> > > 是的，我使用的是cursor的账户，我现在把原来的浏览器登录加上，稍等。
> > 
> > 
> > 谢谢大佬，我还发现登陆的密码是明示的，可能存在泄露的问题，十分感谢，您的产品非常好用
> 
> 已经添加了浏览器登录，这个版本是重构的，有些功能还没加上。新增密码登录是因为很多人使用ssh远程无法使用，没想到你们是GitHub登录，考虑不周了。

已经登陆成功，感谢大佬。十分感谢！！！！！！！！！！！

**Comment by Tianhezhiwai** [comment]
已经登陆成功，感谢大佬。十分感谢！！！！！！！！！！！
