### ISSUE TITLE
希望能支持快捷键

### ISSUE THREAD

**Issue by xiao5gee** [Meteo-Pig/CursorCode#3]
要是可以支持快捷键就更好了，比如选择某段代码，ctrl+L 沟通这段代码的优化方式

**Comment by Meteo-Pig** [comment]
> 要是可以支持快捷键就更好了，比如选择某段代码，ctrl+L 沟通这段代码的优化方式

快捷键之前有想过，但是vscode快捷键太多了，很容易冲突，不知道该设置什么热键为快捷键，你有什么好的建议吗？

**Comment by xiao5gee** [comment]
> > 要是可以支持快捷键就更好了，比如选择某段代码，ctrl+L 沟通这段代码的优化方式
> 
> 快捷键之前有想过，但是vscode快捷键太多了，很容易冲突，不知道该设置什么热键为快捷键，你有什么好的建议吗？

**Comment by xiao5gee** [comment]
对标Cursor官方编译器（Ctrl+L: Chat selection code), 看了下，目前vscode没有这块的快捷键，其他的插件还不清楚；

**Comment by Meteo-Pig** [comment]
> 对标Cursor官方编译器（Ctrl+L: Chat selection code) ？看了下，目前vscode没有这块的快捷键，其他的插件还不清楚；

Ctrl+L （Select current line）已经在vscode中已经被使用了，是选择当前行。

**Comment by Meteo-Pig** [comment]
![WeChat Screenshot_20230326100855](https://user-images.githubusercontent.com/83995869/227773826-88c0a359-616c-4267-bc3d-3245eb1318ad.png)
vscode可以自定义快捷键，在键盘快捷方式中搜索CursorCode，给它添加一个自定义热键即可，前提是这个热键未被使用。
