### ISSUE TITLE
显示效果优化

### ISSUE THREAD

**Issue by xtuer** [Meteo-Pig/CursorCode#7]
搜索 "promise 使用 finally 有风险吗"，部分代码关键字如 finally, then, catch 等不换行显示效果应该会更好 (应该显示为 inline 的样式)。

**Comment by xtuer** [comment]
单独显示的关键字换行了，例如目前显示的效果 `finally` 换行了:

Yes, using
```
finally
```
with promises can have some risks. In JavaScript

---

希望显示的样式

Yes, using `finally` with promises can have some risks. In JavaScript

**Comment by Meteo-Pig** [comment]
已经优化完成并且发布了，请更新一下vscode插件。

**Comment by xtuer** [comment]
哇哦，太感谢了，已经更新，效果很棒，效率真高。
