### ISSUE TITLE
注意到你没有实现continue（连续编辑）

### ISSUE THREAD

**Issue by dev-bz** [Meteo-Pig/CursorCode#9]
我只是提一下，cursor 的api 是用 `continue/` 而不是 `continue`，这是有区别的，不知道你注意到没有，也许这是你卡这的原因。

**Comment by Meteo-Pig** [comment]
> 我只是提一下，cursor 的api 是用 `continue/` 而不是 `continue`，这是有区别的，不知道你注意到没有，也许这是你卡这的原因。

是的，谢谢你的提醒，这很重要，但是现在我在cursor ide里面使用这个continue也不能正常返回内容并且继续编辑，导致我无法进行调试。
